version: "3"
services:
  mysql:
    image: postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    container_name: post-sqlc-postgres
    network_mode: "bridge"