// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type User struct {
	ID                uint64
	Name              string
	PhoneNumber       string
	Otp               sql.NullString
	OtpExpirationTime sql.NullTime
}
