// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :execresult
INSERT INTO users (name, phone_number) VALUES ($1, $2)
`

// query.sql
func (q *Queries) Create(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, create)
}

const get = `-- name: Get :one
SELECT id, name, phone_number, otp, otp_expiration_time FROM users WHERE phone_number = $1
`

func (q *Queries) Get(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, get)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhoneNumber,
		&i.Otp,
		&i.OtpExpirationTime,
	)
	return i, err
}

const update = `-- name: Update :exec
UPDATE users SET otp = $1, otp_expiration_time = $2 WHERE id = $3
`

func (q *Queries) Update(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, update)
	return err
}
